### ISSUE TITLE
Android arm build errors

### ISSUE THREAD

**Issue by scmcom** [aisouard/libwebrtc#48]
Attempting to compile using:
`cmake -DTARGET_OS=android -DTARGET_CPU=arm ..`

Results in the following:
```
[ 66%] Built target webrtc-clang
[ 83%] Generating build files
ERROR at //build/config/android/rules.gni:2676:9: Script returned non-zero exit code.
        exec_script("//build/android/gyp/aar.py",
        ^----------
Current dir: /Users/vzwsam/work2/libwebrtc/out/webrtc/src/out/Release/
Command: python -- /Users/vzwsam/work2/libwebrtc/out/webrtc/src/build/android/gyp/aar.py --input-file ../../third_party/android_support_test_runner/lib/rules-0.5.aar --list
Returned 1.
stderr:

Traceback (most recent call last):
  File "/Users/vzwsam/work2/libwebrtc/out/webrtc/src/build/android/gyp/aar.py", line 114, in <module>
    sys.exit(main())
  File "/Users/vzwsam/work2/libwebrtc/out/webrtc/src/build/android/gyp/aar.py", line 81, in main
    with zipfile.ZipFile(aar_file) as z:
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 756, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory: '../../third_party/android_support_test_runner/lib/rules-0.5.aar'

See //third_party/android_support_test_runner/BUILD.gn:21:1: whence it was called.
android_aar_prebuilt("rules_java") {
^-----------------------------------
See //build/config/android/internal_rules.gni:120:23: which caused the file to be included.
            deps += [ "${_target_label}__build_config" ]
                      ^-------------------------------
make[5]: *** [CMakeFiles/webrtc-generate-complete] Error 1
make[4]: *** [CMakeFiles/webrtc-generate.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [webrtc/stamp/webrtc-src-build] Error 2
make[1]: *** [CMakeFiles/webrtc-src.dir/all] Error 2
make: *** [all] Error 2
```

Any suggestions or solutions to the above would be greatly appreciated.

**Comment by aisouard** [comment]
That line is interesting:

`IOError: [Errno 2] No such file or directory: '../../third_party/android_support_test_runner/lib/rules-0.5.aar'
`

Taking a look right now, perhaps we could officially support Android once it's solved!

**Comment by aisouard** [comment]
In the meantime, you can edit that file at line 58: https://github.com/aisouard/libwebrtc/blob/dev/webrtc/CMakeLists.txt.in#L58

Remove the `--nohooks` flag and try a clean build, I'm not sure why I added this, perhaps for quicker retrieval but that's not the goal anymore, I hope it won't cause any side effect.

**Comment by scmcom** [comment]
Ok great. Will give this a try, many thanks!

**Comment by aisouard** [comment]
It worked, the `--nohooks` flag was added to skip retrieval of testing data, I'll mark that issue as solved once I get it working with the `--nohooks` flag.

**Comment by scmcom** [comment]
I encountered this error on OSX:
```
[ 83%] Built target webrtc-generate
Scanning dependencies of target webrtc-build
[100%] Running ninja
ninja: Entering directory `out/Release'
ninja: error: '../../third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/libgcc.a', needed by 'obj/webrtc/libwebrtc.a', missing and no known rule to make it
make[5]: *** [CMakeFiles/webrtc-build-complete] Error 1
make[4]: *** [CMakeFiles/webrtc-build.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [webrtc/stamp/webrtc-src-build] Error 2
make[1]: *** [CMakeFiles/webrtc-src.dir/all] Error 2
make: *** [all] Error 2
```
Will try on Ubuntu

**Comment by aisouard** [comment]
It seems that Android is exclusively supported under Linux.

https://webrtc.org/native-code/android/
> Android development is only supported on Linux.

**Comment by scmcom** [comment]
Confirmed that it works without --nohooks. Will there be any functional difference in the libs without this flag?

**Comment by aisouard** [comment]
There shouldn't be any difference, this flag prevents the commands defined inside the DEPS file to be executed.

Le 14 juillet 2017 17:54:45 GMT+02:00, samuel charles mindlin <notifications@github.com> a écrit :
>Confirmed that it works without --nohooks. Will there be any functional
>difference in the libs without this flag?
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/aisouard/libwebrtc/issues/48#issuecomment-315396087

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.
