### ISSUE TITLE
Cmake fails on Windows 

### ISSUE THREAD

**Issue by ArJavBi** [aisouard/libwebrtc#52]
Hello, I'm using the current branch version, Visual Studio Community 2015 Update 3 and Windows 10 SDK (10.0.14393) as mentioned on [https://chromium.googlesource.com/chromium/src/+/master/docs/windows_build_instructions.md#Visual-Studio](https://chromium.googlesource.com/chromium/src/+/master/docs/windows_build_instructions.md#Visual-Studio) but I get still the same compile errors like juliao [https://github.com/aisouard/libwebrtc/issues/29]()

What I'm doing wrong?

Thanks in advance.

[buid_output.txt](https://github.com/aisouard/libwebrtc/files/1272972/buid_output.txt)

**Comment by aisouard** [comment]
Hello,

The most interesting part is located there :

```
4>    Fetching gn.exe for win32
4>    0> Failed to fetch file gs://chromium-gn/3b6a35d309aeeba61ba945d91752d1d65acf3d4f for src/buildtools/win/gn.exe, skipping. [Err: Traceback (most recent call last):
4>
4>      File "C:\Projekte\libwebrtc\out\depot_tools\src\depot-tools\gsutil.py", line 160, in <module>
4>
4>        sys.exit(main())
4>
4>      File "C:\Projekte\libwebrtc\out\depot_tools\src\depot-tools\gsutil.py", line 157, in main
4>
4>        clean=args.clean)
4>
4>      File "C:\Projekte\libwebrtc\out\depot_tools\src\depot-tools\gsutil.py", line 125, in run_gsutil
4>
4>        gsutil_bin = ensure_gsutil(force_version, target, clean)
4>
4>      File "C:\Projekte\libwebrtc\out\depot_tools\src\depot-tools\gsutil.py", line 119, in ensure_gsutil
4>
4>        raise InvalidGsutilError()
4>
4>    __main__.InvalidGsutilError
4>
4>    ]
4>    Downloading 1 files took 7.218000 second(s)
4>    Failed to fetch file gs://chromium-gn/3b6a35d309aeeba61ba945d91752d1d65acf3d4f for src/buildtools/win/gn.exe. [Err: Traceback (most recent call last):
4>
4>      File "C:\Projekte\libwebrtc\out\depot_tools\src\depot-tools\gsutil.py", line 160, in <module>
4>
4>        sys.exit(main())
4>
4>      File "C:\Projekte\libwebrtc\out\depot_tools\src\depot-tools\gsutil.py", line 157, in main
4>
4>        clean=args.clean)
4>
4>      File "C:\Projekte\libwebrtc\out\depot_tools\src\depot-tools\gsutil.py", line 125, in run_gsutil
4>
4>        gsutil_bin = ensure_gsutil(force_version, target, clean)
4>
4>      File "C:\Projekte\libwebrtc\out\depot_tools\src\depot-tools\gsutil.py", line 119, in ensure_gsutil
4>
4>        raise InvalidGsutilError()
4>
4>    __main__.InvalidGsutilError
4>
4>    ]
```

I'm not sure if that error is caused by Google right now, perhaps you could try again later or obtain the `gn.exe` file in another way.

Or perhaps the script needs to be updated, they might have moved the gn.exe file elsewhere.
